export const starterKitCommandNames = {
  setParagraph: "setParagraph",
  toggleHeading: "toggleHeading",
  toggleBold: "toggleBold",
  toggleItalic: "toggleItalic",
  toggleCode: "toggleCode",
  toggleStrike: "toggleStrike",
  toggleUnderline: "toggleUnderline",
  toggleBlockquote: "toggleBlockquote",
  toggleCodeBlock: "toggleCodeBlock",
  wrapBulletList: "wrapBulletList",
  wrapOrderedList: "wrapOrderedList",
  liftListItem: "liftListItem",
  sinkListItem: "sinkListItem",
  setLink: "setLink",
  unsetLink: "unsetLink",
  insertHorizontalRule: "insertHorizontalRule",
  insertHardBreak: "insertHardBreak",
  undo: "undo",
  redo: "redo"
} as const;
